-----------boook category

INSERT INTO category (category_name)
VALUES
('Fiction'),
('Non-Fiction'),
('Fantasy'),
('Science Fiction'),
('Mystery'),
('Horror'),
('Romance'),
('Thriller'),
('Historical'),
('Biography'),
('Autobiography'),
('Self-Help'),
('Cookbook'),
('Travel'),
('Guide'),
('Science'),
('Mathematics'),
('Philosophy'),
('Religion'),
('Spirituality'),
('Psychology'),
('Sociology'),
('Anthropology'),
('Economics'),
('Political Science'),
('History'),
('Geography'),
('Law'),
('Education'),
('Linguistics'),
('Literature'),
('Music'),
('Art'),
('Film'),
('Theatre'),
('Dance'),
('Fashion'),
('Design'),
('Architecture'),
('Photography'),
('Culinary'),
('Gardening'),
('Craft'),
('Hobby'),
('Sport'),
('Fitness'),
('Health'),
('Wellness'),
('Beauty'),
('Parenting'),
('Family'),
('Relationship'),
('Marriage');